apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  ttlSecondsAfterFinished: 50
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hello from my first Job!"]
      restartPolicy: Never
